# Generated by Django 5.0.7 on 2024-07-28 11:58

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='برند')),
                ('nationality', models.CharField(max_length=100, verbose_name='ملیت')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام کشور')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='مدل')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='رنگ')),
                ('screen_size', models.PositiveIntegerField(verbose_name='سایز صفحه نمایش')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('unavailable', 'ناموجود')], max_length=12, verbose_name='وضعیت')),
                ('create_at', models.TimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('update_at', models.TimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand', verbose_name='برند')),
                ('manufacturing_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='کشور سازنده')),
            ],
            options={
                'verbose_name': 'موبایل',
                'verbose_name_plural': 'موبایل ها',
            },
        ),
    ]
