# Generated by Django 5.0.7 on 2024-07-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='manufacturing_country',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
