# Generated by Django 5.0.7 on 2024-07-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='screen_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
